/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface TokenVestingInterface extends Interface {
    getFunction(nameOrSignature: "createVesting" | "debugVesting" | "owner" | "releasableAmount" | "release" | "renounceOwnership" | "revoke" | "token" | "transferOwnership" | "vestingSchedules"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "TokensReleased" | "VestingCreated" | "VestingRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'createVesting', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'debugVesting', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'releasableAmount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'release', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'revoke', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'vestingSchedules', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'createVesting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'debugVesting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releasableAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'release', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revoke', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vestingSchedules', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokensReleasedEvent {
      export type InputTuple = [beneficiary: AddressLike, amount: BigNumberish];
      export type OutputTuple = [beneficiary: string, amount: bigint];
      export interface OutputObject {beneficiary: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VestingCreatedEvent {
      export type InputTuple = [beneficiary: AddressLike, amount: BigNumberish, cliff: BigNumberish, duration: BigNumberish];
      export type OutputTuple = [beneficiary: string, amount: bigint, cliff: bigint, duration: bigint];
      export interface OutputObject {beneficiary: string, amount: bigint, cliff: bigint, duration: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VestingRevokedEvent {
      export type InputTuple = [beneficiary: AddressLike, amountReturned: BigNumberish];
      export type OutputTuple = [beneficiary: string, amountReturned: bigint];
      export interface OutputObject {beneficiary: string, amountReturned: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TokenVesting extends BaseContract {
    
    connect(runner?: ContractRunner | null): TokenVesting;
    waitForDeployment(): Promise<this>;

    interface: TokenVestingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createVesting: TypedContractMethod<
      [beneficiary: AddressLike, amount: BigNumberish, cliffDuration: BigNumberish, vestingDuration: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    debugVesting: TypedContractMethod<
      [beneficiary: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {startTime: bigint, cliffDuration: bigint, vestingDuration: bigint, totalAmount: bigint, blockTimestamp: bigint, elapsed: bigint, vestedAmount: bigint }],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    releasableAmount: TypedContractMethod<
      [beneficiary: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    release: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    revoke: TypedContractMethod<
      [beneficiary: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    vestingSchedules: TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, bigint, bigint, bigint, bigint, bigint, boolean] & {beneficiary: string, totalAmount: bigint, released: bigint, startTime: bigint, cliffDuration: bigint, vestingDuration: bigint, revoked: boolean }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createVesting'): TypedContractMethod<
      [beneficiary: AddressLike, amount: BigNumberish, cliffDuration: BigNumberish, vestingDuration: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'debugVesting'): TypedContractMethod<
      [beneficiary: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {startTime: bigint, cliffDuration: bigint, vestingDuration: bigint, totalAmount: bigint, blockTimestamp: bigint, elapsed: bigint, vestedAmount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'releasableAmount'): TypedContractMethod<
      [beneficiary: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'release'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revoke'): TypedContractMethod<
      [beneficiary: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'vestingSchedules'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, bigint, bigint, bigint, bigint, bigint, boolean] & {beneficiary: string, totalAmount: bigint, released: bigint, startTime: bigint, cliffDuration: bigint, vestingDuration: bigint, revoked: boolean }],
      'view'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'TokensReleased'): TypedContractEvent<TokensReleasedEvent.InputTuple, TokensReleasedEvent.OutputTuple, TokensReleasedEvent.OutputObject>;
getEvent(key: 'VestingCreated'): TypedContractEvent<VestingCreatedEvent.InputTuple, VestingCreatedEvent.OutputTuple, VestingCreatedEvent.OutputObject>;
getEvent(key: 'VestingRevoked'): TypedContractEvent<VestingRevokedEvent.InputTuple, VestingRevokedEvent.OutputTuple, VestingRevokedEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'TokensReleased(address,uint256)': TypedContractEvent<TokensReleasedEvent.InputTuple, TokensReleasedEvent.OutputTuple, TokensReleasedEvent.OutputObject>;
      TokensReleased: TypedContractEvent<TokensReleasedEvent.InputTuple, TokensReleasedEvent.OutputTuple, TokensReleasedEvent.OutputObject>;
    

      'VestingCreated(address,uint256,uint256,uint256)': TypedContractEvent<VestingCreatedEvent.InputTuple, VestingCreatedEvent.OutputTuple, VestingCreatedEvent.OutputObject>;
      VestingCreated: TypedContractEvent<VestingCreatedEvent.InputTuple, VestingCreatedEvent.OutputTuple, VestingCreatedEvent.OutputObject>;
    

      'VestingRevoked(address,uint256)': TypedContractEvent<VestingRevokedEvent.InputTuple, VestingRevokedEvent.OutputTuple, VestingRevokedEvent.OutputObject>;
      VestingRevoked: TypedContractEvent<VestingRevokedEvent.InputTuple, VestingRevokedEvent.OutputTuple, VestingRevokedEvent.OutputObject>;
    
    };
  }